import type { Metadata } from "next";
import { Geist, Geist_Mono, Sofia_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/navbar";
import Footer from "@/components/layout/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const sofia_sans = Sofia_Sans({
  subsets: ["latin"],
  variable: "--font-sofia_sans",
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${sofia_sans.variable} bg-[rgba(249,250,251)] antialiased`}
      >
        <Navbar />
        <div className="w-full flex flex-col items-center pt-12 px-6">
          <div className="max-w-[1100px] w-full">{children}</div>
          <div className="max-w-[1100px] w-full">
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
